name: 'contracts'

env:
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  working-directory: packages/subgraph

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - 'packages/subgraph/**'
      - '.github/workflows/subgraph-*.yml'

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 16

      - name: 'Install the dependencies'
        run: 'yarn install'

      - name: 'Lint the code'
        run: 'yarn lint'

      - name: 'Add lint summary'
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: 'Build the subgraph'
        run: 'yarn build'

      - name: 'Test the subgraph'
        run: 'yarn test'

      - name: 'Add test summary'
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
